// Contains some kind of database for the details of the hotels

export const BigCardInfo = [
  {
    id: 0,
    imageSource:(require('../../assets/Images/hotel1.jpeg')),
    rating: '4.8',
    name: 'Emeralda De Hotel',
    location: 'Paris, France',
    price: '$29',
    reviews: '3,789',
  },
  {
    id: 1,
    imageSource:(require('../../assets/Images/hotel2.jpeg')),
    rating: '4.2',
    name: 'President Hotel',
    location: 'Paris, France',
    price: '$35',
    reviews: '4,378',
  },
  {
    id: 2,
    imageSource:(require('../../assets/Images/hotel3.jpeg')),
    rating: '3.9',
    name: 'Palms Casino',
    location: 'Amsterdam, Netherlands',
    price: '$32',
    reviews: '4,293',
  },
  {
    id: 3,
    imageSource:(require('../../assets/Images/hotel4.jpeg')),
    rating: '4.5',
    name: 'Palazzo Versace',
    location: 'Rome, Italy',
    price: '$27',
    reviews: '4,593',
  },
  {
    id: 4,
    imageSource:(require('../../assets/Images/hotel5.jpeg')),
    rating: '4.4',
    name: 'The Venetian',
    location: 'Rotterdam, Netherlands',
    price: '$33',
    reviews: '3,923',
  },
  {
    id: 5,
    imageSource:(require('../../assets/Images/hotel6.jpeg')),
    rating: '3.7',
    name: 'Bird Rock',
    location: 'Istanbul, Turkiye',
    price: '$29',
    reviews: '4,981',
  },
  {
    id: 6,
    imageSource:(require('../../assets/Images/hotel7.jpeg')),
    rating: '4.6',
    name: 'Martinez Hotel',
    location: 'London, England',
    price: '$32',
    reviews: '3,672',
  },
  {
    id: 7,
    imageSource:(require('../../assets/Images/hotel8.jpeg')),
    rating: '4.6',
    name: 'Palazzo Versace',
    location: 'Paris, France',
    price: '$36',
    reviews: '4,672',
  },
  {
    id: 8,
    imageSource:(require('../../assets/Images/hotel9.jpeg')),
    rating: '4.2',
    name: 'Faena Hotel',
    location: 'London, England',
    price: '$26',
    reviews: '4,121',
  },
];